Data loaded correctly
number of classes 70
2024-05-28 20:34:22,380 - training_logger - INFO - Configurations: {'root': '/home/disi/ml', 'img_folder': 'aircraft', 'model_name': 'efficientnetv2', 'data_dir': '/home/disi/ml/datasets/aircraft', 'dataset_name': 'aircraft', 'checkpoint': None, 'save_dir': '/home/disi/ml/checkpoints/efficientnetv2_aircraft_try', 'project_name': 'efficientnetv2_test', 'image_size': 224, 'mean': [0.485, 0.456, 0.406], 'std': [0.229, 0.224, 0.225], 'batch_size': 32, 'epochs': 20, 'optimizer': 'AdamW', 'optimizer_type': 'custom', 'learning_rate': 0.01, 'weight_decay': 0.1, 'momentum': 0.736045219441998, 'criterion': 'CrossEntropyLoss', 'scheduler': True, 'step_size': 10, 'patience': 5, 'dropout_rate': 0.3317332509897824, 'device': 'cuda'}
Traceback (most recent call last):
  File "/home/disi/ml/intromlproject/training-main.py", line 177, in <module>
    main(config)
  File "/home/disi/ml/intromlproject/training-main.py", line 146, in main
    optimizer = create_optimizer(model, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disi/ml/intromlproject/utils/optimizers.py", line 9, in create_optimizer
    optimizer = custom_optimizer(model, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/disi/ml/intromlproject/utils/optimizers.py", line 51, in custom_optimizer
    if config['optim'] == 'SGD':
       ~~~~~~^^^^^^^^^
KeyError: 'optim'